### ISSUE TITLE
Where is pi declared? 

### ISSUE THREAD

**Issue by TuckerHaydon** [radionavlab/gpsImuNode#2]
https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/estimationNode.cpp#L98

I couldn't track it down. Consider using M_PI or defining it as a constexpr in a new file (constants.h?)

**Comment by TuckerHaydon** [comment]
I've seen this variable twice now: SEC_PER_WEEK. Consider creating a constants.h file where all of these are defined.

https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/gpsCallbacks.cpp#L20

https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/gpsCallbacks.cpp#L21

**Comment by TuckerHaydon** [comment]
Consider defining the Eigen::Vector3d gravity vector in the constants file as well.

https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/gpsCallbacks.cpp#L106

**Comment by TuckerHaydon** [comment]
When creating a constants file, adopt a consistent naming strategy. Google suggests camel case starting with the letter k. I like to do all caps with underscores like SEC_PER_WEEK. Just pick something and be consistent. 

https://google.github.io/styleguide/cppguide.html#Constant_Names

**Comment by TuckerHaydon** [comment]
https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/include/classes.hpp#L16

Another SEC_PER_WEEK instance

**Comment by nickMont** [comment]
Added constants.hpp.  Using the caps/underscore convention as well since it's close to what I did with the other package.  Gravity and the IMU rotation matrix are there as well.
