### ISSUE TITLE
rotMatFromEuler

### ISSUE THREAD

**Issue by TuckerHaydon** [radionavlab/gpsImuNode#6]
Consider using the following template. It's pretty easy to read/understand.
```
Eigen::AngleAxisd rollAngle(roll, Eigen::Vector3d::UnitZ());
Eigen::AngleAxisd yawAngle(yaw, Eigen::Vector3d::UnitY());
Eigen::AngleAxisd pitchAngle(pitch, Eigen::Vector3d::UnitX());

Eigen::Quaternion<double> q = rollAngle * yawAngle * pitchAngle;

Eigen::Matrix3d rotationMatrix = q.matrix();
```
https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/mathHelperFunctions.cpp#L175

**Comment by TuckerHaydon** [comment]
https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/mathHelperFunctions.cpp#L8

**Comment by marcelinomalmeidan** [comment]
Are you sure this is correct, Tucker?
Typically yaw is around Z, roll is around X, and pitch is around Y (using
an ENU frame). Are you using a different frame in this case?
Also, the order of roll, pitch and yaw matter. So we might want to be
careful with the following line as well:

Eigen::Quaternion<double> q = rollAngle * yawAngle * pitchAngle;

Marcelino Almeida

2018-07-17 11:14 GMT-05:00 TuckerHaydon <notifications@github.com>:

**Comment by TuckerHaydon** [comment]
For our definition of XYZ/ENU, it doesn't look correct. I took it from a blog post. I was suggesting using the template, not the code directly. For our own euler2RotMat321, it would be:

```
const Eigen::AngleAxisd 3(yaw,   Eigen::Vector3d::UnitZ());
const Eigen::AngleAxisd 2(pitch, Eigen::Vector3d::UnitY());
const Eigen::AngleAxisd 1(roll,  Eigen::Vector3d::UnitX());

const Eigen::Quaternion<double> q = 3*2*1;
const Eigen::Matrix3d R = q.matrix();
```

**Comment by nickMont** [comment]
It's more readable but I'm not sure if it's more/less efficient than typing out each angle.  Regardless, I've rewritten the 321 this way.

**Comment by TuckerHaydon** [comment]
Disregarding efficiency, the reason library calls like this should be used is to prevent minor code bugs. When writing 9 different statements with positive and negative cosines, it's easy to make a sign error mistake.

Just to be safe, have you tested and compared your original function with the new one? Make sure the outputs are the same/both implementations are valid.

**Comment by nickMont** [comment]
It's all good.
