### ISSUE TITLE
Consider attaching a callback for switching between snapdragon and lynx

### ISSUE THREAD

**Issue by TuckerHaydon** [radionavlab/gpsImuNode#8]
https://github.com/radionavlab/gpsImuNode/blob/e1f3c9e98518bdb30e84618e8ae55736daf33202/src/gpsCallbacks.cpp#L236

You configure your program to use the snapdragon or lynx callback only once at the beginning. The callback function is abstracted away.

something like what is done in snap_cam
```
typedef std::function<void(ICameraFrame *frame)> CallbackFunction;

void SnapCam::setListener(CallbackFunction fun)
{
    this->cb_ = fun;
}

void SnapCam::onVideoFrame(ICameraFrame *frame) {
    this->cb_(frame);
}

```

**Comment by nickMont** [comment]
The messages and data types are completely different.  I wrote it to be able to use both simultaneously in case we want to use both (say, if we're able to fix up the vibration issue).
